version: 2.1

##################################### CIRCLECI ORBS ############################################

orbs:
  slack: gsaslis/slack-orb@dev:branch-filters

##################################### CIRCLECI JOBS ############################################

jobs:
  send_slack_status_update_on_failure:
    docker:
      - image: circleci/buildpack-deps:latest
    steps:
      - run: exit 1
      - slack/status:
          fail_only: 'true'

  send_slack_status_update_on_failure_on_master_only:
    docker:
      - image: circleci/buildpack-deps:latest
    steps:
      - run: exit 1
      - slack/status:
          fail_only: 'true'
          only_for_branch: master

##################################### CIRCLECI WORKFLOWS ############################################

workflows:
  version: 2
  some_flow:
    jobs:
      - send_slack_status_update_on_failure
      - send_slack_status_update_on_failure_on_master_only
